### ISSUE TITLE
implementation of player health

### ISSUE THREAD

**Issue by brandonscholten** [nmarhari/SWE-Alpha#11]
- keep track of player health
- player should take damage when they touch lava
- death screen (might be better off as a separate issue)
   - button to reset the game
   - display the user's score

**Comment by nmarhari** [comment]
Should this issue be closed @brandonscholten @Yug3737 ?

**Comment by Yug3737** [comment]
Sure. I can do that. Then do yo mind if I work on the Health bar?

**Comment by Yug3737** [comment]
This issue was converted to player health bar issue.
